# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 00:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20170403_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='balance',
            field=djmoney.models.fields.MoneyField(blank=True, currency_choices=(('USD', 'US Dollar'), ('MXN', 'Mexican Peso')), decimal_places=2, default=Decimal('100'), default_currency='MXN', max_digits=10, null=True, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar'), ('MXN', 'Mexican Peso')], default='MXN', editable=False, max_length=3),
        ),
    ]
